### ISSUE TITLE
Bit Depth Fix and Resources Fix do not work

### ISSUE THREAD

**Issue by Crackers0106** [telvarost/MojangFix-StationAPI#3]
I made sure I had them enabled in the config, but for whatever reason neither of these features work.
I still have messed up clouds and some sounds are still wrong and using the newer ones.

**Comment by telvarost** [comment]
For the resources you should be able to specify where your resources come from using the config. Perhaps a different provider will give you the sounds you want.

Do you have an AMD graphics card? I can look into UniTweaks bit depth fix, could you try running UniTweaks without this mod installed and let me know if it fixes your issue? If it does, I could swap to using that fix instead

**Comment by Crackers0106** [comment]
I do have an AMD gpu, I've used UniTweaks and the fix there does work

**Comment by telvarost** [comment]
Ah, looks like at some point I accidentally deleted the line which says to include the mixin. Releasing a fix for it soon

**Comment by telvarost** [comment]
Completed in https://github.com/telvarost/MojangFix-StationAPI/pull/4
You'll need the newer version of StationAPI, if that's a problem let me know and I can create a special build for you until your other mods get updated to the newest StationAPI
